name: patrickshaffer
favicon: null
layout_spectrum: 0.11718896473757923
typography_spectrum: 0.3800534780602902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6983740106225014
  lightness: 0.3160433352459222
  saturation: 0.19435661332681775
  rhythmicContrast: 0.4675372773781419
purpose: []
